language: php

matrix:
  include:
    - php: 7
      env: LINT=yes QA=yes
    - php: 7.1
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer selfupdate
  - composer install
  - if [ "$LINT" == "yes" ]; then composer global require --update-no-dev sugared-rim/cs; fi
  - if [ "$QA" == "yes" ]; then composer global require --update-no-dev codeclimate/php-test-reporter:dev-master satooshi/php-coveralls; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

script:
  - composer travis
  - if [ "$LINT" == "yes" ]; then composer lint; fi

after_success:
  - if [ "$QA" == "yes" ]; then coveralls -v; fi
  - if [ "$QA" == "yes" ]; then test-reporter; fi

addons:
  code_climate:
    repo_token: 86eb8a3f4eb3e85d3d7c4635f9a5b1f9b0900dc19682ab6493f6f2f919e15236
